/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package equipos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocio.Negocio;


/**
 *
 * @author Manuel
 */
public class JPanelAltaEquipo extends javax.swing.JPanel {

    Negocio negocio = new Negocio();
    
    /**
     * Creates new form JPanelPrincipal
     */
    public JPanelAltaEquipo() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelImagenEquipo = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelHW = new javax.swing.JLabel();
        jLabelSW = new javax.swing.JLabel();
        jLabelPVP = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldHW = new javax.swing.JTextField();
        jTextFieldSW = new javax.swing.JTextField();
        jTextFieldPVP = new javax.swing.JTextField();
        jButtonConfirmarDatos = new javax.swing.JButton();
        jButtonVolverPrincipal = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelImagenEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenEquipo.setMaximumSize(new java.awt.Dimension(38, 17));
        jLabelImagenEquipo.setMinimumSize(new java.awt.Dimension(38, 17));
        jLabelImagenEquipo.setPreferredSize(new java.awt.Dimension(38, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 405, 0, 0);
        jPanel1.add(jLabelImagenEquipo, gridBagConstraints);

        jLabelID.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 342, 0, 0);
        jPanel1.add(jLabelID, gridBagConstraints);

        jLabelEstado.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 342, 0, 0);
        jPanel1.add(jLabelEstado, gridBagConstraints);

        jLabelHW.setText("Hardware");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 342, 0, 0);
        jPanel1.add(jLabelHW, gridBagConstraints);

        jLabelSW.setText("Software");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 342, 0, 0);
        jPanel1.add(jLabelSW, gridBagConstraints);

        jLabelPVP.setText("PVP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 342, 0, 0);
        jPanel1.add(jLabelPVP, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 306);
        jPanel1.add(jTextFieldID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 306);
        jPanel1.add(jTextFieldEstado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 306);
        jPanel1.add(jTextFieldHW, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 306);
        jPanel1.add(jTextFieldSW, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 306);
        jPanel1.add(jTextFieldPVP, gridBagConstraints);

        jButtonConfirmarDatos.setText("CONFIRMAR DATOS");
        jButtonConfirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 342, 170, 0);
        jPanel1.add(jButtonConfirmarDatos, gridBagConstraints);

        jButtonVolverPrincipal.setText("AL MENÚ PRINCIPAL");
        jButtonVolverPrincipal.setBorder(null);
        jButtonVolverPrincipal.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonConfirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosActionPerformed
        String text = "DNI: " + jTextFieldID.getText() + "\nESTADO: " + jTextFieldEstado.getText()+ "\nHW: " + jTextFieldHW.getText() + "\nSW: " + jTextFieldSW.getText() +"\nPVP: " + jTextFieldPVP.getText();
            JOptionPane.showMessageDialog(null, text);
            String[] datos = {jTextFieldID.getText(), jTextFieldEstado.getText(), jTextFieldHW.getText(), jTextFieldSW.getText(), jTextFieldPVP.getText()};
            negocio.insertarEquipo(datos);
    }//GEN-LAST:event_jButtonConfirmarDatosActionPerformed

//<editor-fold defaultstate="collapsed" desc="metodos">
    
    private void initMyComponents(){
        jLabelImagenEquipo.setSize(new Dimension(125, 125));
        negocio.setImageLabel(jLabelImagenEquipo, "src/images/java_equipo.png");
        setColors();
    }
    private void setColors(){
        this.setBackground(new Color(179, 255, 217));
        jPanel1.setBackground(new Color(179, 255, 217));
    }
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarDatos;
    public javax.swing.JButton jButtonVolverPrincipal;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelHW;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImagenEquipo;
    private javax.swing.JLabel jLabelPVP;
    private javax.swing.JLabel jLabelSW;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldHW;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPVP;
    private javax.swing.JTextField jTextFieldSW;
    // End of variables declaration//GEN-END:variables
}
