/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestióngamingcenter;

import Incidencias.JPanelConsultaIncidencia;
import Incidencias.JPanelEliminaciónIncidencia;
import Incidencias.JPanelModificaciónIncidencia;
import Incidencias.JPanelNuevaIncidencia;
import alquileres.JPanelConsultaAlquiler;
import alquileres.JPanelEliminaciónAlquiler;
import alquileres.JPanelModificaciónAlquiler;
import alquileres.JPanelNuevoAlquiler;
import equipos.JPanelModificaciónEquipo;
import equipos.JPanelConsultaEquipo;
import equipos.JPanelAltaEquipo;
import equipos.JPanelBajaEquipo;
import clientes.JPanelConsultaCliente;
import clientes.JPanelModificaciónCliente;
import clientes.JPanelBajaCliente;
import clientes.JPanelAltaCliente;
import facturas.JPanelConsultaFactura;
import facturas.JPanelEliminaciónFactura;
import facturas.JPanelModificaciónFactura;
import facturas.JPanelNuevaFactura;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import negocio.Negocio;


/**
 *
 * @author Manuel
 */
public class General extends javax.swing.JFrame {

    /**
     * Creates new form General
     */
    
    public General() {
        initComponents();
        initMyComponents();
    }
    
    //NEGOCIO
    Negocio negocio = new Negocio();
    
    private final String PANEL_PRINCIPAL = "PANEL_PRINCIPAL";
    //CLIENTES
    private final String PANEL_ALTA_CLIENTE = "PANEL_ALTA_CLIENTE";
    private final String PANEL_BAJA_CLIENTE = "PANEL_BAJA_CLIENTE";
    private final String PANEL_MODIF_CLIENTE = "PANEL_MODIF_CLIENTE";
    private final String PANEL_INFO_CLIENTE = "PANEL_INFO_CLIENTE";
    //EQUIPOS
    private final String PANEL_ALTA_EQUIPO = "PANEL_ALTA_EQUIPO";
    private final String PANEL_BAJA_EQUIPO = "PANEL_BAJA_EQUIPO";
    private final String PANEL_MODIF_EQUIPO = "PANEL_MODIF_EQUIPO";
    private final String PANEL_INFO_EQUIPO = "PANEL_INFO_EQUIPO";
    //ALQUILERES
    private final String PANEL_NUEVO_ALQUILER = "PANEL_NUEVO_ALQUILER";
    private final String PANEL_ELIMINACIÓN_ALQUILER = "PANEL_ELIMINACIÓN_ALQUILER";
    private final String PANEL_MODIF_ALQUILER = "PANEL_MODIF_ALQUILER";
    private final String PANEL_INFO_ALQUILER = "PANEL_INFO_ALQUILER";
    //INCIDENCIAS
    private final String PANEL_NUEVA_INCIDENCIA = "PANEL_NUEVA_INCIDENCIA";
    private final String PANEL_ELIMINACIÓN_INCIDENCIA = "PANEL_ELIMINACIÓN_INCIDENCIA";
    private final String PANEL_MODIF_INCIDENCIA = "PANEL_MODIF_INCIDENCIA";
    private final String PANEL_INFO_INCIDENCIA = "PANEL_INFO_INCIDENCIA";
    //FACTURAS
    private final String PANEL_NUEVA_FACTURA = "PANEL_NUEVA_FACTURA";
    private final String PANEL_ELIMINACIÓN_FACTURA = "PANEL_ELIMINACIÓN_FACTURA";
    private final String PANEL_MODIF_FACTURA = "PANEL_MODIF_FACTURA";
    private final String PANEL_INFO_FACTURA = "PANEL_INFO_FACTURA";
    
//DECLARACIÓN DE PANELES
    JPanelPrincipal jPanelPrin = new JPanelPrincipal();
    //CLIENTES
    JPanelAltaCliente jPanelAC = new JPanelAltaCliente();
    JPanelBajaCliente jPanelBC = new JPanelBajaCliente();
    JPanelModificaciónCliente jPanelMC = new JPanelModificaciónCliente();
    JPanelConsultaCliente jPanelCC = new JPanelConsultaCliente();
    //EQUIPOS
    JPanelAltaEquipo jPanelAE = new JPanelAltaEquipo();
    JPanelBajaEquipo jPanelBE = new JPanelBajaEquipo();
    JPanelModificaciónEquipo jPanelME = new JPanelModificaciónEquipo();
    JPanelConsultaEquipo jPanelCE = new JPanelConsultaEquipo();
    //ALQUILERES
    JPanelNuevoAlquiler jPanelNA = new JPanelNuevoAlquiler();
    JPanelEliminaciónAlquiler jPanelEA = new JPanelEliminaciónAlquiler();
    JPanelModificaciónAlquiler jPanelMA = new JPanelModificaciónAlquiler();
    JPanelConsultaAlquiler jPanelCA = new JPanelConsultaAlquiler();
    //INCIDENCIAS
    JPanelNuevaIncidencia jPanelNI = new JPanelNuevaIncidencia();
    JPanelEliminaciónIncidencia jPanelEI = new JPanelEliminaciónIncidencia();
    JPanelModificaciónIncidencia jPanelMI = new JPanelModificaciónIncidencia();
    JPanelConsultaIncidencia jPanelCI = new JPanelConsultaIncidencia();
    //FACTURAS
    JPanelNuevaFactura jPanelNF = new JPanelNuevaFactura();
    JPanelEliminaciónFactura jPanelEF = new JPanelEliminaciónFactura();
    JPanelModificaciónFactura jPanelMF = new JPanelModificaciónFactura();
    JPanelConsultaFactura jPanelCF = new JPanelConsultaFactura();
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemAltaCliente = new javax.swing.JMenuItem();
        jMenuItemBajaCliente = new javax.swing.JMenuItem();
        jMenuItemModifCliente = new javax.swing.JMenuItem();
        jMenuItemConsultaCliente = new javax.swing.JMenuItem();
        jMenuEquipos = new javax.swing.JMenu();
        jMenuItemAltaEquipo = new javax.swing.JMenuItem();
        jMenuItemBajaEquipo = new javax.swing.JMenuItem();
        jMenuItemModifEquipo = new javax.swing.JMenuItem();
        jMenuItemConsultaEquipo = new javax.swing.JMenuItem();
        jMenuAlquileres = new javax.swing.JMenu();
        jMenuItemNuevoAlquiler = new javax.swing.JMenuItem();
        jMenuItemEliminarAlquiler = new javax.swing.JMenuItem();
        jMenuItemModifAlquiler = new javax.swing.JMenuItem();
        jMenuItemConsultarAlquiler = new javax.swing.JMenuItem();
        jMenuFacturas = new javax.swing.JMenu();
        jMenuItemNuevaFactura = new javax.swing.JMenuItem();
        jMenuItemEliminarFactura = new javax.swing.JMenuItem();
        jMenuItemModifFactura = new javax.swing.JMenuItem();
        jMenuItemConsultarFactura = new javax.swing.JMenuItem();
        jMenuIncidencias = new javax.swing.JMenu();
        jMenuItemNuevaIncidencia = new javax.swing.JMenuItem();
        jMenuItemEliminarIncidencia = new javax.swing.JMenuItem();
        jMenuItemModifIncidencia = new javax.swing.JMenuItem();
        jMenuItemConsultarIncidencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContenedor.setLayout(new java.awt.CardLayout());

        jMenuClientes.setText("Clientes");

        jMenuItemAltaCliente.setText("Alta de cliente");
        jMenuItemAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemAltaCliente);

        jMenuItemBajaCliente.setText("Baja de cliente");
        jMenuItemBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemBajaCliente);

        jMenuItemModifCliente.setText("Modificar cliente");
        jMenuItemModifCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemModifCliente);

        jMenuItemConsultaCliente.setText("Consultar cliente");
        jMenuItemConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemConsultaCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuEquipos.setText("Equipos");

        jMenuItemAltaEquipo.setText("Alta de equipo");
        jMenuItemAltaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaEquipoActionPerformed(evt);
            }
        });
        jMenuEquipos.add(jMenuItemAltaEquipo);

        jMenuItemBajaEquipo.setText("Baja de equipo");
        jMenuItemBajaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaEquipoActionPerformed(evt);
            }
        });
        jMenuEquipos.add(jMenuItemBajaEquipo);

        jMenuItemModifEquipo.setText("Modificar equipo");
        jMenuItemModifEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifEquipoActionPerformed(evt);
            }
        });
        jMenuEquipos.add(jMenuItemModifEquipo);

        jMenuItemConsultaEquipo.setText("Consultar equipo");
        jMenuItemConsultaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaEquipoActionPerformed(evt);
            }
        });
        jMenuEquipos.add(jMenuItemConsultaEquipo);

        jMenuBar1.add(jMenuEquipos);

        jMenuAlquileres.setText("Alquileres");

        jMenuItemNuevoAlquiler.setText("Nuevo alquiler");
        jMenuItemNuevoAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoAlquilerActionPerformed(evt);
            }
        });
        jMenuAlquileres.add(jMenuItemNuevoAlquiler);

        jMenuItemEliminarAlquiler.setText("Eliminar alquiler");
        jMenuItemEliminarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarAlquilerActionPerformed(evt);
            }
        });
        jMenuAlquileres.add(jMenuItemEliminarAlquiler);

        jMenuItemModifAlquiler.setText("Modificar alquiler");
        jMenuItemModifAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifAlquilerActionPerformed(evt);
            }
        });
        jMenuAlquileres.add(jMenuItemModifAlquiler);

        jMenuItemConsultarAlquiler.setText("Consultar alquiler");
        jMenuItemConsultarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarAlquilerActionPerformed(evt);
            }
        });
        jMenuAlquileres.add(jMenuItemConsultarAlquiler);

        jMenuBar1.add(jMenuAlquileres);

        jMenuFacturas.setText("Facturas");

        jMenuItemNuevaFactura.setText("Nueva Factura");
        jMenuItemNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaFacturaActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jMenuItemNuevaFactura);

        jMenuItemEliminarFactura.setText("Eliminar Factura");
        jMenuItemEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarFacturaActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jMenuItemEliminarFactura);

        jMenuItemModifFactura.setText("Modificar Factura");
        jMenuItemModifFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifFacturaActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jMenuItemModifFactura);

        jMenuItemConsultarFactura.setText("Consultar Factura");
        jMenuItemConsultarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarFacturaActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jMenuItemConsultarFactura);

        jMenuBar1.add(jMenuFacturas);

        jMenuIncidencias.setText("Incidencias");

        jMenuItemNuevaIncidencia.setText("Nueva Incidencia");
        jMenuItemNuevaIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaIncidenciaActionPerformed(evt);
            }
        });
        jMenuIncidencias.add(jMenuItemNuevaIncidencia);

        jMenuItemEliminarIncidencia.setText("Eliminar Incidencia");
        jMenuItemEliminarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarIncidenciaActionPerformed(evt);
            }
        });
        jMenuIncidencias.add(jMenuItemEliminarIncidencia);

        jMenuItemModifIncidencia.setText("Modificar Incidencia");
        jMenuItemModifIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifIncidenciaActionPerformed(evt);
            }
        });
        jMenuIncidencias.add(jMenuItemModifIncidencia);

        jMenuItemConsultarIncidencia.setText("Consultar Incidencia");
        jMenuItemConsultarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarIncidenciaActionPerformed(evt);
            }
        });
        jMenuIncidencias.add(jMenuItemConsultarIncidencia);

        jMenuBar1.add(jMenuIncidencias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaClienteActionPerformed
        showPanel(PANEL_BAJA_CLIENTE);
    }//GEN-LAST:event_jMenuItemBajaClienteActionPerformed

    private void jMenuItemAltaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaEquipoActionPerformed
        showPanel(PANEL_ALTA_EQUIPO);
    }//GEN-LAST:event_jMenuItemAltaEquipoActionPerformed

    private void jMenuItemModifIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifIncidenciaActionPerformed
        showPanel(PANEL_MODIF_INCIDENCIA);
    }//GEN-LAST:event_jMenuItemModifIncidenciaActionPerformed

    private void jMenuItemAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaClienteActionPerformed
        showPanel(PANEL_ALTA_CLIENTE);
    }//GEN-LAST:event_jMenuItemAltaClienteActionPerformed

    private void jMenuItemModifClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifClienteActionPerformed
        showPanel(PANEL_MODIF_CLIENTE);
    }//GEN-LAST:event_jMenuItemModifClienteActionPerformed

    private void jMenuItemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaClienteActionPerformed
        showPanel(PANEL_INFO_CLIENTE);
    }//GEN-LAST:event_jMenuItemConsultaClienteActionPerformed

    private void jMenuItemBajaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaEquipoActionPerformed
        showPanel(PANEL_BAJA_EQUIPO);
    }//GEN-LAST:event_jMenuItemBajaEquipoActionPerformed

    private void jMenuItemConsultaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaEquipoActionPerformed
        showPanel(PANEL_INFO_EQUIPO);
    }//GEN-LAST:event_jMenuItemConsultaEquipoActionPerformed

    private void jMenuItemModifEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifEquipoActionPerformed
        showPanel(PANEL_MODIF_EQUIPO);
    }//GEN-LAST:event_jMenuItemModifEquipoActionPerformed

    private void jMenuItemNuevoAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoAlquilerActionPerformed
        showPanel(PANEL_NUEVO_ALQUILER);
    }//GEN-LAST:event_jMenuItemNuevoAlquilerActionPerformed

    private void jMenuItemEliminarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarAlquilerActionPerformed
        showPanel(PANEL_ELIMINACIÓN_ALQUILER);
    }//GEN-LAST:event_jMenuItemEliminarAlquilerActionPerformed

    private void jMenuItemModifAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifAlquilerActionPerformed
        showPanel(PANEL_MODIF_ALQUILER);
    }//GEN-LAST:event_jMenuItemModifAlquilerActionPerformed

    private void jMenuItemConsultarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarAlquilerActionPerformed
        showPanel(PANEL_INFO_ALQUILER);
    }//GEN-LAST:event_jMenuItemConsultarAlquilerActionPerformed

    private void jMenuItemNuevaIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaIncidenciaActionPerformed
        showPanel(PANEL_NUEVA_INCIDENCIA);
    }//GEN-LAST:event_jMenuItemNuevaIncidenciaActionPerformed

    private void jMenuItemEliminarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarIncidenciaActionPerformed
        showPanel(PANEL_ELIMINACIÓN_INCIDENCIA);
    }//GEN-LAST:event_jMenuItemEliminarIncidenciaActionPerformed

    private void jMenuItemConsultarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarIncidenciaActionPerformed
        showPanel(PANEL_INFO_INCIDENCIA);
    }//GEN-LAST:event_jMenuItemConsultarIncidenciaActionPerformed

    private void jMenuItemNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaFacturaActionPerformed
        showPanel(PANEL_NUEVA_FACTURA);
    }//GEN-LAST:event_jMenuItemNuevaFacturaActionPerformed

    private void jMenuItemEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarFacturaActionPerformed
        showPanel(PANEL_ELIMINACIÓN_FACTURA);
    }//GEN-LAST:event_jMenuItemEliminarFacturaActionPerformed

    private void jMenuItemModifFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifFacturaActionPerformed
        showPanel(PANEL_MODIF_FACTURA);
    }//GEN-LAST:event_jMenuItemModifFacturaActionPerformed

    private void jMenuItemConsultarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarFacturaActionPerformed
        showPanel(PANEL_INFO_FACTURA);
    }//GEN-LAST:event_jMenuItemConsultarFacturaActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }
    //<editor-fold defaultstate="collapsed" desc="panels">
    private void initPanels(){
        //INIT IN FULLSCREEN
        this.setExtendedState(MAXIMIZED_BOTH);
        
        //GESTIÓN DE PANELES
        jPanelContenedor.add(jPanelPrin, PANEL_PRINCIPAL);
        jPanelContenedor.add(jPanelAC, PANEL_ALTA_CLIENTE);
        jPanelContenedor.add(jPanelBC, PANEL_BAJA_CLIENTE);
        jPanelContenedor.add(jPanelMC, PANEL_MODIF_CLIENTE);
        jPanelContenedor.add(jPanelCC, PANEL_INFO_CLIENTE);
        jPanelContenedor.add(jPanelBE, PANEL_BAJA_EQUIPO);
        jPanelContenedor.add(jPanelAE, PANEL_ALTA_EQUIPO);
        jPanelContenedor.add(jPanelCE, PANEL_INFO_EQUIPO);
        jPanelContenedor.add(jPanelME, PANEL_MODIF_EQUIPO);
        jPanelContenedor.add(jPanelNA, PANEL_NUEVO_ALQUILER);
        jPanelContenedor.add(jPanelEA, PANEL_ELIMINACIÓN_ALQUILER);
        jPanelContenedor.add(jPanelMA, PANEL_MODIF_ALQUILER);
        jPanelContenedor.add(jPanelCA, PANEL_INFO_ALQUILER);
        jPanelContenedor.add(jPanelNI, PANEL_NUEVA_INCIDENCIA);
        jPanelContenedor.add(jPanelEI, PANEL_ELIMINACIÓN_INCIDENCIA);
        jPanelContenedor.add(jPanelMI, PANEL_MODIF_INCIDENCIA);
        jPanelContenedor.add(jPanelCI, PANEL_INFO_INCIDENCIA);
        jPanelContenedor.add(jPanelNF, PANEL_NUEVA_FACTURA);
        jPanelContenedor.add(jPanelEF, PANEL_ELIMINACIÓN_FACTURA);
        jPanelContenedor.add(jPanelMF, PANEL_MODIF_FACTURA);
        jPanelContenedor.add(jPanelCF, PANEL_INFO_FACTURA);
        
        //ACTION LISTENERS
        jPanelPrin.jButtonAltaCliente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_ALTA_CLIENTE);
            }
        });
        jPanelPrin.jButtonAltaDeEquipo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_ALTA_EQUIPO);
            }
        });
        jPanelPrin.jButtonNuevoAlquiler.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_NUEVO_ALQUILER);
            }
        });
        jPanelPrin.jButtonNuevaFactura.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_NUEVA_FACTURA);
            }
        });
        
        //BOTONES DE REGRESO
        jPanelAC.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelBC.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelMC.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelCC.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelBE.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelAE.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelCE.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelME.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelNA.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelEA.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelMA.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelCA.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelNI.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelEI.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelMI.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelCI.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelNF.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelEF.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelMF.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        jPanelCF.jButtonVolverPrincipal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showPanel(PANEL_PRINCIPAL);
            }
        });
        
    }
//</editor-fold>
    
    
    //<editor-fold defaultstate="collapsed" desc="métodos">
    private void initMyComponents(){
        showPanel(PANEL_PRINCIPAL);
        initPanels();
        negocio.crearConexión();
    }
    //MOSTRAR PANELES
    private void showPanel(String panel){
        CardLayout cl = (CardLayout) jPanelContenedor.getLayout();
        cl.show(jPanelContenedor, panel);
    }
//</editor-fold>

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAlquileres;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEquipos;
    private javax.swing.JMenu jMenuFacturas;
    private javax.swing.JMenu jMenuIncidencias;
    private javax.swing.JMenuItem jMenuItemAltaCliente;
    private javax.swing.JMenuItem jMenuItemAltaEquipo;
    private javax.swing.JMenuItem jMenuItemBajaCliente;
    private javax.swing.JMenuItem jMenuItemBajaEquipo;
    private javax.swing.JMenuItem jMenuItemConsultaCliente;
    private javax.swing.JMenuItem jMenuItemConsultaEquipo;
    private javax.swing.JMenuItem jMenuItemConsultarAlquiler;
    private javax.swing.JMenuItem jMenuItemConsultarFactura;
    private javax.swing.JMenuItem jMenuItemConsultarIncidencia;
    private javax.swing.JMenuItem jMenuItemEliminarAlquiler;
    private javax.swing.JMenuItem jMenuItemEliminarFactura;
    private javax.swing.JMenuItem jMenuItemEliminarIncidencia;
    private javax.swing.JMenuItem jMenuItemModifAlquiler;
    private javax.swing.JMenuItem jMenuItemModifCliente;
    private javax.swing.JMenuItem jMenuItemModifEquipo;
    private javax.swing.JMenuItem jMenuItemModifFactura;
    private javax.swing.JMenuItem jMenuItemModifIncidencia;
    private javax.swing.JMenuItem jMenuItemNuevaFactura;
    private javax.swing.JMenuItem jMenuItemNuevaIncidencia;
    private javax.swing.JMenuItem jMenuItemNuevoAlquiler;
    public javax.swing.JPanel jPanelContenedor;
    // End of variables declaration//GEN-END:variables
}
