/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package facturas;

import equipos.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import negocio.Negocio;


/**
 *
 * @author Manuel
 */
public class JPanelEliminaciónFactura extends javax.swing.JPanel {

    Negocio negocio = new Negocio();
    
    /**
     * Creates new form JPanelPrincipal
     */
    public JPanelEliminaciónFactura() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelImagenFactura = new javax.swing.JLabel();
        jLabelNumFactura = new javax.swing.JLabel();
        jTextFieldNumFactura = new javax.swing.JTextField();
        jButtonConfirmarDatos = new javax.swing.JButton();
        jButtonVolverPrincipal = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelImagenFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenFactura.setMaximumSize(new java.awt.Dimension(38, 17));
        jLabelImagenFactura.setMinimumSize(new java.awt.Dimension(38, 17));
        jLabelImagenFactura.setPreferredSize(new java.awt.Dimension(38, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 405, 0, 0);
        jPanel1.add(jLabelImagenFactura, gridBagConstraints);

        jLabelNumFactura.setText("Núm de factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 342, 0, 0);
        jPanel1.add(jLabelNumFactura, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 306);
        jPanel1.add(jTextFieldNumFactura, gridBagConstraints);

        jButtonConfirmarDatos.setText("CONFIRMAR DATOS");
        jButtonConfirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 342, 170, 0);
        jPanel1.add(jButtonConfirmarDatos, gridBagConstraints);

        jButtonVolverPrincipal.setText("AL MENÚ PRINCIPAL");
        jButtonVolverPrincipal.setBorder(null);
        jButtonVolverPrincipal.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonConfirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmarDatosActionPerformed

 //<editor-fold defaultstate="collapsed" desc="metodos">
    
    private void initMyComponents(){
        jLabelImagenFactura.setSize(new Dimension(125, 125));
        negocio.setImageLabel(jLabelImagenFactura, "src/images/java_factura.png");
        setColors();
    }
    private void setColors(){
        this.setBackground(new Color(179, 255, 217));
        jPanel1.setBackground(new Color(179, 255, 217));
    }
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarDatos;
    public javax.swing.JButton jButtonVolverPrincipal;
    private javax.swing.JLabel jLabelImagenFactura;
    private javax.swing.JLabel jLabelNumFactura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNumFactura;
    // End of variables declaration//GEN-END:variables
}
